apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubernetes-gated-deployments.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kubernetes-gated-deployments.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubernetes-gated-deployments.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kubernetes-gated-deployments.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-service-account
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CONTROLLER_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: POLLER_INTERVAL_MILLISECONDS
              value: {{ .Values.pollerIntervalMilliseconds | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
